import LegalLayout from './LegalLayout';

export default function Terms() {
  return (
    <LegalLayout
      eyebrow="Legal"
      title="Terms & Conditions"
      updated="May 25, 2026"
    >
      <div className="legal-callout">
        <p>
          <strong>Tickr is not a professional financial platform.</strong> It is a personal
          project for educational and informational use only. Nothing on this site is
          financial advice. You are solely responsible for your own investment decisions and
          for any gains or losses that result from them. Use the app at your own risk.
        </p>
      </div>

      <p>
        These Terms & Conditions ("Terms") govern your access to and use of Tickr ("the
        app"). By creating an account or otherwise using the app, you agree to these Terms.
        If you do not agree, do not use the app.
      </p>

      <h2>1. What Tickr is — and what it isn't</h2>
      <p>
        Tickr is a personal project developed and operated by one individual. It pulls
        publicly available stock news and prices, runs the headlines through an open
        sentiment model (FinBERT-tone), and lets you record a personal portfolio for
        your own tracking.
      </p>
      <p>
        Tickr is <strong>not</strong> a broker, a financial advisor, an investment
        adviser, an exchange, or a professional financial platform. It does not execute
        trades, hold funds, or recommend securities. No content in the app should be
        interpreted as financial, investment, tax, accounting, or legal advice.
      </p>

      <h2>2. No financial advice</h2>
      <p>
        Sentiment scores, headline summaries, charts, "verdicts," and any other output
        generated by the app are produced by an automated model from public news and price
        feeds. They may be wrong, stale, incomplete, or misleading. Do not rely on them to
        make investment decisions. Consult a licensed professional before acting on any
        financial matter.
      </p>

      <h2>3. Use at your own risk — no liability for financial loss</h2>
      <p>
        You acknowledge and agree that:
      </p>
      <ul>
        <li>All use of Tickr is entirely at your own risk.</li>
        <li>
          The app's developer is <strong>not responsible for any financial loss</strong>,
          missed opportunity, damages, or other harm arising from your use of, or
          inability to use, the app — whether direct, indirect, incidental, consequential,
          or otherwise.
        </li>
        <li>
          Market data, news, and sentiment classifications may be delayed, inaccurate,
          incomplete, or temporarily unavailable.
        </li>
        <li>
          You are solely responsible for verifying any information before acting on it.
        </li>
      </ul>

      <h2>4. "As is" — no warranties</h2>
      <p>
        The app is provided "as is" and "as available", without warranties of any kind,
        express or implied. The developer disclaims, to the maximum extent permitted by
        law, all warranties including merchantability, fitness for a particular purpose,
        accuracy, reliability, uptime, and non-infringement.
      </p>

      <h2>5. Accounts</h2>
      <p>
        You are responsible for keeping your password secure and for all activity on your
        account. Provide accurate information when signing up, and notify us if you suspect
        unauthorized access. Accounts that abuse the service or violate these Terms may be
        suspended or removed at any time.
      </p>

      <h2>6. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Scrape, mirror, or republish the app's data or pages without permission.</li>
        <li>Use the app to attempt to harm, overload, or probe security of the service.</li>
        <li>Use the app to violate any law or another person's rights.</li>
        <li>Resell, redistribute, or commercialize access to the app.</li>
      </ul>

      <h2>7. Third-party data and services</h2>
      <p>
        Tickr depends on third-party data providers (Finnhub, Alpha Vantage), open-source
        models (FinBERT-tone via Hugging Face), and hosting infrastructure (Microsoft
        Azure). Those services have their own terms and may change, fail, or rate-limit at
        any time. The developer makes no guarantees about their availability or accuracy.
      </p>

      <h2>8. Intellectual property</h2>
      <p>
        The Tickr name, code, and visual design belong to the developer. Sentiment models,
        underlying data, and third-party content remain the property of their respective
        owners and are subject to their own licenses.
      </p>

      <h2>9. Termination</h2>
      <p>
        You may stop using the app and request account deletion at any time. The developer
        may suspend or shut down the service, or any account, at any time and for any
        reason, including ceasing the project entirely.
      </p>

      <h2>10. Changes to these Terms</h2>
      <p>
        These Terms may be updated as the project evolves. Continued use of the app after
        an update means you accept the revised Terms.
      </p>

      <h2>11. Governing law</h2>
      <p>
        To the extent legally enforceable for an informal personal project, any disputes
        will be governed by the laws of your local jurisdiction without regard to its
        conflict of laws principles. Mandatory consumer rights in your jurisdiction are not
        affected.
      </p>

      <h2>12. Contact</h2>
      <p>
        <strong>Note:</strong> This app is a personal project developed by one person. If
        there are any questions or concerns please let me know here:{' '}
        <a href="mailto:adityagyawali535@gmail.com">adityagyawali535@gmail.com</a>.
      </p>
    </LegalLayout>
  );
}
